import {
  FaCalendar,
  FaMapMarkerAlt,
  FaBriefcase,
  FaRegCalendarAlt,
  FaGithub,
  FaStar,
  FaCodeBranch,
  FaUsers,
  FaBook,
  FaLink,
  FaTwitter,
  FaRegClock,
  FaLinkedin,
  FaInstagram,
  FaArrowDown,
  FaHeart,
  FaGithubSquare,
  FaInstagramSquare,
  FaTimes,
  FaBars,
} from "react-icons/fa";
import { HiCode, HiOutlineOfficeBuilding } from "react-icons/hi";
import { MdEmail } from "react-icons/md";

export {
  FaCalendar,
  FaMapMarkerAlt,
  FaBriefcase,
  HiCode,
  HiOutlineOfficeBuilding,
  FaRegCalendarAlt,
  FaGithub,
  FaStar,
  FaCodeBranch,
  FaUsers,
  FaBook,
  FaLink,
  FaTwitter,
  FaRegClock,
  FaLinkedin,
  FaInstagram,
  FaArrowDown,
  MdEmail,
  FaHeart,
  FaGithubSquare,
  FaInstagramSquare,
  FaTimes,
  FaBars,
};
